### ISSUE TITLE
Finesse doesn't build using Meson

### ISSUE THREAD

**Issue by vaastav** [fsgeek/finesse#4]
I tried building Finesse using Meson but it doesn't build as it complains that libfuse is missing.
I am using  meson version 0.54.2.

Here is the error log when I try the cmd  ```meson ..``` in the build folder.

Build type: native build
Project name: libfuse3
Project version: 3.9.1
C compiler for the host machine: cc (gcc 5.5.0 "cc (Ubuntu 5.5.0-12ubuntu1~16.04) 5.5.0 20171010")
C linker for the host machine: cc ld.bfd 2.26.1
Host machine cpu family: x86_64
Host machine cpu: x86_64
Checking for function "fork" : YES 
Checking for function "fstatat" : YES 
Checking for function "openat" : YES 
Checking for function "readlinkat" : YES 
Checking for function "pipe2" : YES 
Checking for function "splice" : YES 
Checking for function "vmsplice" : YES 
Checking for function "posix_fallocate" : YES 
Checking for function "fdatasync" : YES 
Checking for function "utimensat" : YES 
Checking for function "copy_file_range" : NO 
Checking for function "fallocate" : YES 
Checking for function "setxattr" : YES 
Checking for function "iconv" : YES 
Checking whether type "struct stat" has member "st_atim" : YES 
Checking whether type "struct stat" has member "st_atimespec" : NO 
Configuring config.h using configuration
../meson.build:68: WARNING: Consider using the built-in warning_level option instead of using "-Wall".
../meson.build:68: WARNING: Consider using the built-in warning_level option instead of using "-Wextra".
../meson.build:72: WARNING: Consider using the built-in warning_level option instead of using "-Wall".
../meson.build:72: WARNING: Consider using the built-in warning_level option instead of using "-Wextra".
../meson.build:72: WARNING: Consider using the built-in option for language standard version instead of using "-std=c++11".
Message: Compiler warns about unused result even when casting to void
Run-time dependency threads found: YES
Library uuid found: YES
Library rt found: YES
Library uuid found: YES

../finesse/communications/meson.build:5:0: ERROR: C library 'libfuse' not found

**Comment by fsgeek** [comment]
I wasn't able to reproduce the issue, but we don't need the libfuse dependency for the communications package anyway, so I've removed it in 365f179.  If that fixes it, we can close the issue.  If not, I'll need to figure out a better repro case for it.

**Comment by vaastav** [comment]
Now, I get the same error but for the util package instead.

../finesse/util/meson.build:4:0: ERROR: C library 'libfuse' not found

**Comment by fsgeek** [comment]
I've removed libfuse dependency from all the other finesse subdirectories, since it isn't needed in any of them. Let's hope that fixes it.

**Comment by vaastav** [comment]
That seems to have done the trick,
